on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: CI
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      - name: Post comment
        uses: mshick/add-pr-comment@v1
        with:
            message: |
              "hellow"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
